name: Test

on:
    push:
        branches: [ development, master ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 7.3 ]
                node: [ 10 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@2.10.0
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node }}
            -   name: Install dependencies
                run: composer update
            -   name: Run test suite
                env:
                    PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
                run: composer run test
