name: Test

on:
    push:
        branches: [ development, master ]
    pull_request:
        branches: [ development, master ]
    schedule:
        - cron: 0 3 * * 1,3,5
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 7.4, 8.0, 8.1 ]
            fail-fast: false
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: 14
            -   name: Init composer dependencies
                run: composer update
            -   name: Install dependencies (Codeception v4)
                run: composer update codeception/codeception:^4.0 codeception/module-webdriver codeception/module-phpbrowser -W
            -   name: Setup Firefox
                uses: browser-actions/setup-firefox@latest
            -   name: Run test suite (Codeception v4)
                env:
                    PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
                run: composer run test
            -   name: Install dependencies (Codeception v5)
                run: composer update codeception/codeception:^5.0 codeception/module-webdriver codeception/module-phpbrowser -W
                if: matrix.php == '8.0' || matrix.php == '8.1'
            -   name: Run test suite (Codeception v5)
                env:
                    PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
                run: composer run test
                if: matrix.php == '8.0' || matrix.php == '8.1'
